### ISSUE TITLE
make available the requests_cache backend configuration

### ISSUE THREAD

**Issue by alexandru-u** [indigo-dc/flaat#12]
Hi, 

Thank you for Flaat! 

While using it with a Flask application on Azure AppService, we encountered an Azure bug: https://github.com/Azure/azure-sdk-for-python/issues/6503. This is because Flaat uses requests_cache with a default configuration using SQLite, which is the object of that bug.
Can you provide a Flaat API to set/configure the backend for requests_cache? (I can confirm it works on Azure with memory configured as backend)

Cheers,
Alexandru

PS I can do a Pull Request, if you don't have the time to add this functionality

**Comment by marcvs** [comment]
Thanks for this information.

PRs will be appreciated, as I can currently not promise to work on this timely. 
But I will try my best to improve flaat, because we use it internally, too.

**Comment by marcvs** [comment]
I've added some code (quick and not exactly clean). The caveat is that a default cache instance will be created, when you import flaat.  You can later change that. If this works for you I'll merge that branch (make-cache-configurable) to master.
Can you confirm, please.

**Comment by alexandru-u** [comment]
Marcvs, thank you for your quick response. I have tested your make-cache-configurable branch. For us not to encounter that Azure bug, we would need to have the backend initialized by 'memory' and not by 'sqlite' in issuertools.py->Cache_options()->__init__(self)->self.backend = **'sqlite'**. If the backend is initialized by default to 'memory', no cache.sqlite file is created(thus no Azure bug triggered) and everything seems to be working fine.

**Comment by marcvs** [comment]
Ok, I've changed the default to memory.  Does it work now?

**Comment by alexandru-u** [comment]
As I previously mentioned, it works (no Azure bug) with the backend default initialized to 'memory'. Thank you!

**Comment by alexandru-u** [comment]
Marcvs, do you know when this feature will be available via the flaat release via PyPI?

**Comment by marcvs** [comment]
I've just uploaded it.
