### ISSUE TITLE
Variable referenced before assignment

### ISSUE THREAD

**Issue by maricaantonacci** [indigo-dc/flaat#18]
Hi,

while testing flaat integration, I noticed the following:
- the  variable 'resp' is referenced before assignment at [issuertools.py#L220](https://github.com/indigo-dc/flaat/blob/cbd64a7f5c218b6818db10d10ebb2351159adf66/flaat/issuertools.py#L220)
- the timeout for calling userinfo endpoint is hard-coded and set to 1.2s, which is too small in my case (I'm testing against a test instance of INDIGO IAM). AFAIU Flaat provides the method set_client_connect_timeout() to configure the "[timeout for flaat connecting to OPs](https://github.com/indigo-dc/flaat/blob/master/flaat/__init__.py#L142)" but this is not used in issuertools.py, right?

**Comment by marcvs** [comment]
Thanks for these points. I'll look into this asap.
