### ISSUE TITLE
Testing needs Environment example

### ISSUE THREAD

**Issue by marcvs** [indigo-dc/flaat#51]
The tests are nice. Just: I fail to give a proper environment e.g. for the `CLAIM_GROUP`.

Tried variants of this, without success:
```
$ export FLAAT_ISS=https://aai.egi.eu/oidc/; export OIDC_AGENT_ACCOUNT=egi; export CLAIM_GROUP='"{["marcus","user"]}"'
$ pytest flaat/aio/aio_test.py -v
```

**Comment by lburgey** [comment]
Please read the "development" section of the documentation.
