### ISSUE TITLE
'Flaat' object has no attribute 'set_timeout'

### ISSUE THREAD

**Issue by BorjaEst** [indigo-dc/flaat#54]
I have the following error:
```py
Exception has occurred: AttributeError
'Authorization' object has no attribute 'set_timeout'
```

It looks it is renamed to `set_request_timeout`, however the example it is still outdated:
https://github.com/indigo-dc/flaat/blob/b0d72027038a12fe9529ea91da676fc4725f569f/examples/example_flask.py#L46

**Comment by dianagudu** [comment]
I believe only the `aiohttp` example is up to date, `flask` and `fastapi` need some work (e.g. also use of outdated requirements `ValidLogin` and `HasGroup`).

**Comment by marcvs** [comment]
Right; The other examples still need to be adapted to the new flaat
