### ISSUE TITLE
trusted issuers

### ISSUE THREAD

**Issue by zachmann** [indigo-dc/flaat#74]
My comment is related to `flaat-userinfo`.

When is use `flaat-userinfo` with an AT from an issuer not known to flaat, I get an `Error: Issuer not trusted:`

I cannot find an option to work around this, there seems to be `--my-config` option, but I cannot find information how that config file should look like.

I just want to display the information about the token. I don't understand why I get the error at all when using a JWT. The issuer is inside the token and is correctly obtained by flaat, but it refuses to do something.

There should be at least an command line option to skip/trust an issuer.

**Comment by marcvs** [comment]
Option `--trust-any` (or `--any`), added in v1.1.9 fixes this
