### ISSUE TITLE
Unit tests not working

### ISSUE THREAD

**Issue by vrbanecd** [indigo-dc/flaat#79]
Hi!

When I added the patch to solve our issue we also included some unit tests to [issuers_test.py](https://github.com/indigo-dc/flaat/blob/master/flaat/tests/issuers_test.py)to test the patch. However, we couldn't run the unit test locally- some packages don't seem to be working anymore.

**Comment by marcvs** [comment]
Did you try `tox -e pytest` ?
That installs the dependencie (pytest < 8 is the one that I identified recently)
